src/app/views.py
from urllib import request
from flask import Blueprint, render_template, request
from sqlalchemy import func, distinct, and_, or_, not_

from . import db
from .models import Doctors

from .queries import get_districts_normalized, get_medical_specialty, get_clk_graduates, get_docs_cnt_range, get_student_citizenship

import pandas as pd


views = Blueprint('views', __name__)


@views.route('/mapa', methods=['GET', 'POST'])
def map():
    if request.method == 'POST':
        param_kwargs = {
            'clk_ratio': int(request.form.get('clk_ratio')),
            'pred_year': int(request.form.get('pred_year')),
            'senior_age': int(request.form.get('senior_age')),
            'hours_weekly': int(request.form.get('hours_weekly')),
            'ms_value': request.form.get('medical_specialty'),
            'map_title': f'Výkonnostní kapacita - {request.form.get("medical_specialty")}',
        }
    else:
        param_kwargs = {
            'clk_ratio': 72,
            'pred_year': 2021,
            'senior_age': 65,
            'hours_weekly': 40,
            'ms_value': 'všechny specializace',
            'map_title': f'Výkonnostní kapacita - všechny specializace',
        }
    print(param_kwargs)

    from .predictions import pred_map

    map_kwargs = pred_map(param_kwargs)

    return render_template('map.html',
                           **map_kwargs,
                           **param_kwargs,
                           )

# -------------------------------------------------------------


@views.route('/news')
def news():
    return render_template('news.html')

# -------------------------------------------------------------


@views.route('/about')
def about():
    return render_template('about.html')

# -------------------------------------------------------------


@views.route('/dashboard')
def dashboard():
    return render_template('dashboard.html')

# -------------------------------------------------------------


@ views.route('/', methods=['GET', 'POST'])
def home():
    map_kwargs = {
        'legend_title': 'Počet lékařů / 10 tis. obyv.',
        'ratio_label': ' / 10 000 obyvatel',
        'map_coloring': 'capacity_map'
    }

    ms_value = request.form.get('medical_specialty')
    if request.method == 'POST' and ms_value != 'všechny specializace' and not '--' in ms_value:
        # print(ms_value)
        doctor_cnt = db.session.query(
            Doctors.district,
            func.count(distinct(Doctors.doctor_id))
        ).group_by(Doctors.district).filter(Doctors.medical_specialty == ms_value)
    else:
        ms_value = 'všechny specializace'
        doctor_cnt = db.session.query(
            Doctors.district,
            func.count(distinct(Doctors.doctor_id))
        ).group_by(Doctors.district)

    map_kwargs['ms_value'] = ms_value
    map_kwargs['map_title'] = 'Počet lékařů - ' + ms_value

    doctor_df = pd.DataFrame(doctor_cnt, columns=['district', 'n_doctors'])

    # Medical specialty query
    map_kwargs['medical_specialties'] = get_medical_specialty()

    demo_df, normalized = get_districts_normalized()
    map_kwargs['normalized_names'] = normalized

    df = pd.merge(doctor_df, demo_df, on='district')
    df['ratio'] = round(10000 * df.n_doctors / df.population, 2)
    df = df.sort_values('ratio', ascending=False).reset_index(drop=True)
    map_kwargs['data'] = pd.Series(
        df.ratio.values, index=df.normalized).to_dict()

    # legend labels
    vals = list(df['ratio'].quantile(
        [.2, .3, .5, .65, .75, .90, .95]).values)
    map_kwargs['legend_labels'] = [round(n, 2)
                                   for n in vals] + ['Data nedostupná']

    return render_template('home.html',
                           **map_kwargs,
                           top5=df.head(),
                           worst5=df.tail().iloc[::-1]
                           )

# -------------------------------------------------------------


def age_map():
    map_kwargs = {
        'map_title': 'Průměrný věk lékařů',
        'legend_title': 'Průměrný věk',
        'ratio_label': ' let',
        'map_coloring': 'age_map'
    }

    # demographics query
    demo_df, normalized = get_districts_normalized()
    map_kwargs['normalized_names'] = normalized

    # doctors age query
    doctor_cnt = db.session.query(
        Doctors.district,
        Doctors.age_estimate
    ).distinct(Doctors.district, Doctors.doctor_id)

    doctor_df = pd.DataFrame(doctor_cnt, columns=[
                             'district', 'age_estimate'])
    doctor_df = pd.merge(doctor_df, demo_df, on='district')[
        ['normalized', 'age_estimate']]
    district_ages = doctor_df.groupby(
        'normalized').mean().apply(lambda x: round(x, 2)).sort_values('age_estimate')
    ages = pd.Series(district_ages.age_estimate.values,
                     index=district_ages.index).to_dict()

    map_kwargs['data'] = ages
    # legend labels

    map_kwargs['legend_labels'] = [
        50, 52, 55, 58, 60, 'Data nedostupná']

    return map_kwargs


def new_doctors():
    new_doctors_kwargs = {
    }

    new_docs_cnt = get_docs_cnt_range(year_from=2012, year_to=2021)

    new_doctors_kwargs['new_doctors'] = new_docs_cnt
    new_doctors_kwargs['years'] = list(range(2012, 2022))

    new_doctors_kwargs['graduates'] = get_clk_graduates()

    return new_doctors_kwargs


def students():
    students_kwargs = {
    }

    graduated = get_student_citizenship()

    students_kwargs['graduated_czechs'] = graduated[graduated.citizenship ==
                                                    'CZE']['count'].to_list()

    students_kwargs['graduated_slovaks'] = graduated[graduated.citizenship ==
                                                     'SVK']['count'].to_list()

    students_kwargs['graduated_others'] = graduated[graduated.citizenship ==
                                                    'Ostatní']['count'].to_list()

    return students_kwargs


@ views.route('/statistiky')
def statistics():

    map_kwargs = age_map()

    new_doctors_kwargs = new_doctors()

    student_kwargs = students()

    # TODO create and upload statistics
    return render_template('statistics.html',
                           **map_kwargs,
                           **new_doctors_kwargs,
                           **student_kwargs)

src/app/templates/about.html
{% extends "base.html" %} {% block title %}O projektu - {% endblock %} {% block
content %}
<div class="container">
  <h1>O projektu</h1>
  <p>
    Léčba je nedílnou součástí lidské společnosti již od pravěku, dávno před
    vznikem prvních civilizací. Za léčitele byli původně označování šamani a
    kouzelníci, kteří příčiny nemocí hledali v nadpřirozenu a neduhy léčili
    pomocí rituálů či bylinek. S vývojem lidské rasy, vznikem starověkých
    civilizací a pokrokem s tímto spjatým se obor posouval stále více vpřed až
    vznikla jedna z prvních věd - lékařství. Její zakladatel, Hyppokratés, viděl
    naprosto zřejmé důvody proč tento vědní obor založit. Společnost si
    vytvořila sociální a citové vazby na konkrétní jedince, kteří si (většinou)
    přejí prožít co nejdelší život, nebo je společnost na nich závislá díky
    jejich unikátním zkušenostem a dovednostem. Nesmíme tak zapomenout i na
    čistě praktický důvod, který je v moderní civilizaci již na ústupu, ale v
    některých oblastech světa je stále velmi zásadní. Lidská reprodukce je
    časově náročná a ztráta jakéhokoliv vyspělého jedince může být pro určitou
    skupinu kritická (např. z hlediska pracovní síly). Proto lékařství vždy
    patřilo mezi nejdůležitější obory vědy. Tak je tomu i dodnes.
    <br />
    Přestože došlo k vymýcení či výraznému potlačení mnoha nemocí, důsledkem
    moderního městského životního stylu se objevují stále nové civilizační
    choroby. Reakcemi na tyto události a nemoci jsou vzniky stále nových technik
    a lékařských oborů. Tím dochází ke štěpení této vědy na konkrétní
    specializace. V dnešní době je lékařství tak obsáhlá věda, že je těžko
    představitelné, aby byl lékař expertem na všechny její podoblasti, a proto
    se specializuje na jednu (nebo několik málo) činností. Pokud je obor již
    zastaralý, nemoci vymýcené, obor přirozeně zaniká.
    <br />
    Nemoci se na území České republiky neobjevují pouze lokálně, ale v rámci
    prakticky stejných životních podmínek a malé geografické rozlohy se
    vyskytují po celé zemi. Pomineme-li vznik ohnisek, které se ale také mohou
    objevit prakticky kdekoliv. Obyvatelstvo celé této země by mělo mít
    zaručenou určitou zdravotnickou péči, což je přímo ustanoveno v zákoně č.
    372/2011 Sb., o zdravotních službách a podmínkách jejich poskytování, ve
    znění pozdějších předpisů. Z tohoto důvodu je nutné, aby byla
    celorepublikově dostatečně pokrytá potřebná zdravotnická péče v co nejširším
    rozsahu. Je nepředstavitelné, aby například osoba bydlící v Karlovarském
    kraji, musela dojíždět ke stomatologovi nebo ortopedovi do jiného kraje a
    přitom neměla vhodnější alternativu.
    <br />
    Již nějakou dobu stojí Česká republika na hraně propasti. Podle tiskové
    zprávy České lékařské komory nedostatek lékařů ohrožuje kvalitu zdravotnické
    péče. Za hlavní důvody jsou označeny stárnutí lékařské komunity, exodus
    lékařů do zahraničí a nedostatečné pracovní podmínky (především nedostatečné
    finanční ohodnocení a nadměrná fyzická i psychická zátěž). Lékaři stárnou a
    podle hrubých propočtů ministerstva zdravotnictví jich do roku 2030 odejde
    třetina do důchodu. Tuto díru by měli zaplnit noví lékaři, především
    absolventi vysokých škol. Mnoho z nich však z finančních důvodů opouští
    Českou republiku a stěhuje se za prací do západních zemí, zejména Německa a
    Velké Británie. Nedostatek nových lékařů tak způsobuje nadměrnou pracovní
    zátěž pro ty stávající. Mnozí z nich musí nadále pracovat i přes dosažený
    důchodový věk. Bez této skupiny se podle odborníků některé obory
    zdravotnictví mohou zhroutit. Svoji nemalou roli hrála v posledních letech
    také epidemiologická situace, která vyžadovala vyšší počty lékařského i
    nelékařského zdravotnického personálu. Dokazuje to i skutečnost, že Česká
    republika na počátku roku 2021 nedokázala poskytnout zdravotnickou péči svým
    občanům a musela tak požádat o pomoc sousední státy. V Ústeckém kraji je u
    lékařů evidován mezi létem 2019 a létem 2021 nárůst volných pracovních pozic
    ve výši 20 \%. I tento nedostatek může vést ke snížení kapacity,
    nedostatečnému pokrytí ordinačních hodin či redukci lůžek, a tedy k
    nedostatečné dostupnosti zdravotní péče v daném regionu.

    <br />
    Hlavním cílem této práce je zpracování a analýza aktuálního pokrytí
    lékařských oborů v závislosti na území a populaci a vytvoření mapy
    dostupnosti zdravotnické péče v ČR s následnou predikcí vývoje v
    nadcházejících 3 letech. Nedílnou součástí této práce je získání nezbytných
    dat od různých lékařských institucí, škol, případně pojišťoven pro realizaci
    zvoleného tématu, ideálně v rozmezí posledních 5 - 10 let. Analýza těchto
    dat pomůže především včas odhalit problematická místa a obory, tak aby bylo
    možné systematicky předcházet výpadkům zdravotní péče napříč celou Českou
    republikou. Dalším cílem je vytvoření internetové aplikace, která bude
    srozumitelná a dostupná nejen zdravotnickým institucím, ale i široké
    veřejnosti. Nová aplikace bude sloužit k upozornění na kritické lékařské i
    geografické oblasti a hrozící nedostupnost zdravotnické péče v budoucnosti.
    Práce je zároveň koncipována tak, aby dokázala reagovat na aktuální vývoj
    situace a aby v případě aktualizace a poskytnutí nových dat dokázala
    přemodelovat stávající trendy a reflektovat skutečnost, což se poté odrazí i
    v následné predikci vývoje. Všechny zdravotní instituce, pojišťovny i školy
    se tak budou moci díky získaným znalostem zaměřit na problémové specializace
    a místa a dle svého uvážení motivovat stávající i budoucí lékaře k úspěšnému
    pokrytí zdravotnické péče v České republice. Veřejnost získá povědomí o
    rozložení sil lékařského personálu a díky dostupným informacím může
    například upozornit státní orgány na vznikající problém nebo se rozhodnout o
    migraci do dané lokality.
    <br />
    Součást této práce tvoří i twitterový účet
    <a href="https://twitter.com/Lekari_v_CR"> Dostupnost lékařské péče v ČR </a
    >, jehož cílem bylo dostat tento projekt do povědomí širší veřejnosti.
  </p>
</div>
{% endblock %}

src/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static',filename='style.css') }}"
    />

    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <link
      rel="icon"
      href="https://www.pngall.com/wp-content/uploads/2016/06/Doctor-Symbol-Caduceus-Free-Download-PNG.png"
    />

    {% block head %}{% endblock %}

    <title>{% block title %}{% endblock %} Mapa zdraví</title>
  </head>

  <body>
    <!-- HEADER -->
    <nav class="navbar navbar-expand-lg p-3 navbar-dark bg-dark text-light">
      <img
        src="https://www.citypng.com/public/uploads/small/11639360387mkrjjyvpivdj0abphk62tbisvxfntvdhb93bv78rpd5gtolbrkakfetjkhg2ol21mrlfxibrweiefg0h66pnxqm0q1yrso4bgzvc.png"
        width="30"
        height="20"
      />
      <a class="navbar-brand" href="{{ url_for('views.home') }}">Mapa zdraví</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          
          <a class="nav-item nav-link" id="mapa" href="/mapa">Mapa</a>
          <a class="nav-item nav-link" id="statistiky" href="/statistiky"
            >Statistiky</a
          >
          <a class="nav-item nav-link" id="dashboard" href="/dashboard"
            >Dashboard</a
          >
          <a class="nav-item nav-link" id="news" href="/news">Aktuality</a>
          <a class="nav-item nav-link" id="about" href="/about">O projektu</a>
        </div>
      </div>
      <ul class="navbar-nav navbar-right">
        <li class="nav-item">
          <a
            class="nav-link"
            href="https://twitter.com/Lekari_v_CR"
            target="_blank"
          >
            <i class="fab fa-twitter"></i>
            Twitter
          </a>
        </li>
        <li class="nav-item">
          <a
            class="nav-link"
            href="https://github.com/opendatalabcz/mapa-zdravi"
            target="_blank"
          >
            <i class="fab fa-github"></i>
            GitHub
          </a>
        </li>
      </ul>
    </nav>
    <!-- HEADER END -->

    <!-- MAIN PART -->
    {% block content %} {% endblock %}
    <!-- MAIN PART END -->

    <!-- FOOTER -->
    <footer>
      <div class="footer p-3 bg-dark mt-4 text-light">
        <div class="row align-items-center">
          <div class="col text-center text-lg-left">
            <p class="mb-1">
              Garček Jan,
              <i>Dostupnost zdravotnické péče v České republice</i> [online].
              Diplomová práce. Praha: ČVUT, Fakulta informačních technologií &
              OpenDataLab, 2023. Dostupné z <a href = "https://dspace.cvut.cz/handle/10467/107228.">https://dspace.cvut.cz/handle/10467/107228</a>.
            </p>
            <!-- Provozovatel neodpovídá za správnost a úplnost zpracovaných dat a informací, ani tato neověřuje a zříká se zodpovědnosti za veškeré škody a újmy, které by použitím těchto dat mohly vzniknout.  -->
            <p class="mb-1">
              Zdroje dat:
              <i
                >ČLK, ČSK, ČSÚ, Lékařské fakulty VŠ ČR, vybrané pojišťovny ČR</i
              >
              <p class="mb-1">Kontakt: <a href = "mailto: honzagarcek@gmail.com">honzagarcek@gmail.com</a></p>

            </p>
          </div>
          <div class="col-lg-auto text-center mt-3 mt-lg-0">
            <a href="https://fit.cvut.cz/" target="_blank">
              <img
                class="footer"
                src="{{ url_for('static',filename='img/fit_cvut.svg') }}"
              />
            </a>
            &nbsp;
            <!-- <a href="https://opendatalab.cz/" target="_blank">
              <img
                class="footer"
                src="{{ url_for('static',filename='img/opendatalab.jpg') }}"
              />
            </a> -->
            <a href="https://opendatalab.cz/" target="_blank">
              <img
              class="footer"
              src="{{ url_for('static',filename='img/opendatalab_no_background.png') }}"
            />
          </a>
          </div>
        </div>
      </div>
    </footer>
    <!-- FOOTER END -->

    <!-- SCRIPTS -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='js/index.js') }}"
    ></script>
    <script
      src="https://unpkg.com/leaflet@1.9.2/dist/leaflet.js"
      integrity="sha256-o9N1jGDZrf5tS+Ft4gbIK7mYMipq9lqpVJ91xHSyKhg="
      crossorigin=""
    ></script>

    {% block scripts %} {% endblock %}
    <!-- SCRIPTS END -->
  </body>
</html>

src/app/templates/dashboard.html
{% extends "base.html" %} {% block head %} {% endblock %}{% block title
%}Dashboard - {% endblock %} {% block content %}
<div class="container">
  <h1>Dashboard</h1>
  <p class="message">Připravujeme.</p>
</div>
{% endblock %}

src/app/templates/home.html
{% extends "base.html" %} {% block head %}

<link
  rel="stylesheet"
  href="https://unpkg.com/leaflet@1.9.2/dist/leaflet.css"
  integrity="sha256-sA+zWATbFveLLNqWO2gtiw3HL/lh1giY/Inf1BJ0z14="
  crossorigin=""
/>

{% endblock %} {% block title %}{% endblock %} {% block content %}

<div class="p-3">
  <div class="container">
    <h1>Hlavní stránka</h1>

    Vítejte na stránkách <strong>Dostupnosti lékařské péče v České republice.</strong> <br> 
    Tento projekt vznikl jako diplomová práce na Fakultě informačních technologíí ČVUT
    ve spolupráci s laboratoří OpenDataLab. Motivaci k tvorbě tohoto projektu
    naleznete v záložce <a href="/about">O projektu</a>. Záložka
    <a href="/mapa">Mapa</a> zobrazuje predikci dostupnosti v závislosti na
    vybraných parametrech a v oddílu <a href="/statistiky">Statistiky</a> jsou k
    dispozici vizualizace vybraných dat použitých v tomto projektu.
  </div>

  <div class="container">

    <h3>
      Počet lékařů v jednotlivých krajích
    </h3>
    </br>
    <form method="POST" action="/" align="center">
      <strong>Lékařská specializace:</strong>
      <select
        name="medical_specialty"
        id="medical_specialty"
        onchange="this.form.submit()"
      >
        <option value="všechny specializace">-- vyberte --</option>
        {% for med_spec in medical_specialties %}
          {% if med_spec.medical_specialty_name == ms_value  %}
            <option value="{{med_spec.medical_specialty_name}}" selected>
              {{med_spec.medical_specialty_name}}
            </option>
          {% else %}
          <option value="{{med_spec.medical_specialty_name}}">
            {{med_spec.medical_specialty_name}}
          </option>
          {% endif %}
        {% endfor %}
      </select>
    </form>
  <br />
  <div
    id="map"
    class="leaflet-container leaflet-touch leaflet-retina leaflet-fade-anim leaflet-touch-zoom leaflet-gesture-handling"
  ></div>
</div>

  <div class="container">
    <table class="table table-hover item-list table-striped">
      <thead class="thead-dark">
        <tr>
          <th scope="col"></th>
          <th scope="col">Top {{top5.shape[0]}} okresů</th>
          <th scope="col">Počet doktorů / 10 000 obyv.</th>
        </tr>
      </thead>
      <tbody>
        {% for i, row in top5.iterrows() %}
        <tr>
          <th class="tg-vhup">{{i+1}}</th>
          <th class="tg-vhup">{{row['district']}}</th>
          <th class="tg-vhup">{{row['ratio']}}</th>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

    <div class="container">
    <table class="table table-hover item-list table-striped">
      <thead class="thead-dark">
        <tr>
          <th scope="col"></th>
          <th scope="col">Nejhorších {{worst5.shape[0]}} okresů</th>
          <th scope="col">Počet doktorů / 10 000 obyv.</th>
        </tr>
      </thead>
      <tbody>
        {% for i, row in worst5.iterrows() %}
        <tr>
          <th class="tg-vhup">{{i+1}}</th>
          <th class="tg-vhup">{{row['district']}}</th>
          <th class="tg-vhup">{{row['ratio']}}</th>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %} {% block scripts %}

<script
  type="text/javascript"
  src="{{ url_for('static', filename='geojson/regions.json') }}"
></script>
<script type="text/javascript">
  var legend_labels ={{legend_labels|safe}};
  var data ={{data|safe}};
  var normalized_names = {{normalized_names|safe}};
  var legend_title = JSON.parse('{{legend_title| tojson|safe}}');
  var map_title = {{map_title|tojson|safe}};
  var map_coloring = JSON.parse('{{map_coloring| tojson|safe}}');
  var ratio_label = {{ratio_label|tojson|safe}};
</script>

<script
  type="text/javascript"
  src="{{ url_for('static', filename='js/map.js') }}"
></script>

{% endblock %}

src/app/templates/map.html
{% extends "base.html" %} {% block head %}

<link
  rel="stylesheet"
  href="https://unpkg.com/leaflet@1.9.2/dist/leaflet.css"
  integrity="sha256-sA+zWATbFveLLNqWO2gtiw3HL/lh1giY/Inf1BJ0z14="
  crossorigin=""
/>

{% endblock %} {% block title %}Mapa - {% endblock %}{% block content %}
<div class="container">
  <h1>Predikce dostupnosti lékařské péče</h1>
</div>
<div class="container">
  <h3 >Mapa</h1>
  <form method="POST" action="/mapa" class="form" align="center">
    <div class="form-group">
      <label for="medical_specialty"
        ><strong>Lékařská specializace:</strong></label
      >
      <select
        name="medical_specialty"
        id="medical_specialty"
        onchange="this.form.submit()"
      >
        <option value="všechny specializace">-- vyberte --</option>
        {% for med_spec in medical_specialties %} {% if med_spec == ms_value %}
        <option value="{{med_spec}}" selected>{{med_spec}}</option>
        {% else %}
        <option value="{{med_spec}}">{{med_spec}}</option>
        {% endif %} {% endfor %}
      </select>
    </div>
    <div class="form-group">
      <label for="pred_year" class="hovertext" data-hover="Predikce: 2022-2026"
        ><strong>Rok:</strong></label
      >
      <input
        class="slider"
        type="range"
        min="2020"
        max="2026"
        value="{{pred_year}}"
        id="pred_year"
        name="pred_year"
        oninput="pred_year_out.value = pred_year.value"
        onchange="this.form.submit()"
      />
      <output id="pred_year_out">{{pred_year}}</output>
    </div>

    <div class="form-group">
      <label
        for="clk_ratio"
        class="hovertext"
        data-hover="Poměr mezi lékaři zapsanými do ČLK/ČSK a absolventy lékařských fakult VŠ
        v daném roce"
        ><strong>ČLK ratio:</strong></label
      >
      <input
        class="slider"
        type="range"
        min="1"
        max="100"
        value="{{clk_ratio}}"
        id="clk_ratio"
        name="clk_ratio"
        oninput="clk_ratio_out.value = clk_ratio.value/100"
        onchange="this.form.submit()"
      />
      <output id="clk_ratio_out">{{clk_ratio/100}}</output>
    </div>

    <div class="form-group">
      <label
        for="senior_age"
        class="hovertext"
        data-hover="Věk odchodu lékařů do důchodu"
        ><strong>Důchodový věk:</strong></label
      >
      <input
        class="slider"
        type="range"
        min="60"
        max="75"
        value="{{senior_age}}"
        id="senior_age"
        name="senior_age"
        oninput="senior_age_out.value = senior_age.value"
        onchange="this.form.submit()"
      />
      <output id="senior_age_out">{{senior_age}} let</output>
    </div>

    <div class="form-group">
      <label
        for="hours_weekly"
        class="hovertext"
        data-hover="Počet pracovních hodin pro lékaře za týden"
        ><strong>Počet hodin:</strong></label
      >
      <input
        class="slider"
        type="range"
        min="30"
        max="100"
        value="{{hours_weekly}}"
        id="hours_weekly"
        name="hours_weekly"
        oninput="hours_weekly_out.value = hours_weekly.value"
        onchange="this.form.submit()"
      />
      <output id="hours_weekly_out">{{hours_weekly}}h týdně</output>
    </div>
  </form>
  <br>
  <div
    id="map"
    class="leaflet-container leaflet-touch leaflet-retina leaflet-fade-anim leaflet-touch-zoom leaflet-gesture-handling"
  ></div>
</div>
{% endblock %} {% block scripts %}

<script
  type="text/javascript"
  src="{{ url_for('static', filename='geojson/regions.json') }}"
></script>
<script type="text/javascript">
  var legend_labels ={{legend_labels|safe}};
  var data ={{data|safe}};
  var normalized_names = {{normalized_names|safe}};
  var legend_title = JSON.parse('{{legend_title| tojson|safe}}');
  var map_title = {{map_title|tojson|safe}};
  var map_coloring = JSON.parse('{{map_coloring| tojson|safe}}');
  var ratio_label = {{ratio_label|tojson|safe}};
</script>

<script
  type="text/javascript"
  src="{{ url_for('static', filename='js/map.js') }}"
></script>

{% endblock %}